### ISSUE TITLE
in-fighting feature

### ISSUE THREAD

**Issue by dumptruckDS** [dumptruckDS/progs_dump_qc#114]
bmFbr and ILike80sRock have created a solution for this in their respective forks. PR and testing needed.

**Comment by dumptruckDS** [comment]
@jjelliott I haven't reviewed this code yet. Could this be used to make a monster mad at a func_breakable for example? Or is this just limited to other monsters?

**Comment by jjelliott** [comment]
It doesn't currently work against a breakable. I'll look to see if that's a possible addition.
