### ISSUE TITLE
alternate damage type for Hellknight projectiles

### ISSUE THREAD

**Issue by dumptruckDS** [dumptruckDS/progs_dump_qc#116]
Add selectable damage types (e.g. explosions) to Hellknight projectiles. Requested by Mista Heita

Look into the same for other enemies.

**Comment by jjelliott** [comment]
Started on this.

- Added a projexpl key
- Got the projectiles exploding
- Currently working on adding additional settings for the projexpl key:
  1 - All explode
  2 - Every other spike is exploding
  3 - The spikes are randomly exploding or not
  
Still todo on initial version:
- Add skin/model customization to exploding projectiles so users can differentiate them
- Create HK specific explosion function (just using the rocket grunt one right now)
