### ISSUE TITLE
[Bug] Mobot Vore projectiles

### ISSUE THREAD

**Issue by dumptruckDS** [dumptruckDS/progs_dump_qc#137]
In "mobot" versions of Vores, projectiles do not track.

Possible fix is to set a default to `self.homing` in mobot function.

**Comment by jjelliott** [comment]
Ah, yeah, I forgot that mobots basically replace the spawn function. I’ll take a look later.

**Comment by dumptruckDS** [comment]
No worries. Just wanted to note it for later. There's no rush and I'll try to fix it and ping you if I get stuck.
