### ISSUE TITLE
rmq-items.qc is present but goes unused

### ISSUE THREAD

**Issue by walshawi** [dumptruckDS/progs_dump_qc#74]
In addition to items.qc, the repo also contains a file named rmq-items.qc (obviously a copy of the RMQ items code) which isn't compiled as part of the mod. I've found this mildly problematic, because when I do a search or search-and-replace in all of the *.qc files, I often end up in this file, and have to remember that I need to ignore it and/or go into items.qc instead.

It would be really nice if this file could either (A) be removed, or (B) moved into a new subdirectory (for example, a subdirectory named "unused" or "reference" to make it clear that the file isn't used).

**Comment by dumptruckDS** [comment]
Roger that. In the past I've kept unused qc files for reference but I do things differently now. I'll commit this right away.

**Comment by dumptruckDS** [comment]
resolved in d97296987dd6d4eb23f18ca6c4008ef77c369a0a
