### ISSUE TITLE
[Bug] Different files use different end-of-line encodings

### ISSUE THREAD

**Issue by walshawi** [dumptruckDS/progs_dump_qc#75]
This is a common issue for Quake mods: some of the files in the repo have Windows-style CRLF line endings, some have Unix/Linux/Mac-style LF line endings, and at least one file has a mixture of the two. This can cause different issues for people on different systems using different tools to work with the files.

A Git repo can be configured so that it stores the files in a normalized format, so that the Git client can automatically convert to or from whatever scheme is appropriate for the user's system (so Windows users get CRLF, and pretty much everyone else gets LF).

HOWEVER, trying to implement this now would almost certainly cause merge conflicts with unmerged branches. The best time to try to address this would be when the code for the next version is finalized and all branches have been merged.

When we get to that point, I could send you a PR which will implement the above?

I'm posting this here both to ask whether this is OK and so I don't forget about it!

**Comment by dumptruckDS** [comment]
Yes of course. This is a bit over my head so I trust your judgement.
