### ISSUE TITLE
Typo in start.bsp

### ISSUE THREAD

**Issue by walshawi** [dumptruckDS/progs_dump_qc#78]
This is about the progs_dump start.bsp, not the QuakeC code.

I just noticed that the message in front of the portal that leads to pd_void reads:

"pd_void
func_void, func_bob
and more"

... it should read "trigger_void" instead of "func_void".

**Comment by dumptruckDS** [comment]
LOL thank you! Will fix.

**Comment by dumptruckDS** [comment]
Due to the way I package up the mod at the end of development this won't be fixed until shortly before the actual next release.

**Comment by dumptruckDS** [comment]
fixed in 1.1.2.1
