### ISSUE TITLE
collision for misc_model

### ISSUE THREAD

**Issue by razvanab** [dumptruckDS/progs_dump_qc#89]
Can you please add collision for misc_model ?

**Comment by dumptruckDS** [comment]
We're looking onto it currently.

**Comment by razvanab** [comment]
Thank you.

**Comment by dumptruckDS** [comment]
@razvanab FYI you can use a brush textured with clip to fake a bounding box for your models.

**Comment by razvanab** [comment]
I will try that
Thanks.

**Comment by dumptruckDS** [comment]
We've decide to close this issue as clip brushes are the best way to handle this.
